unicode_support: fix error handling for missing PyICU.
Fixes: e050715739f3f74a41365ba6e87425c9cf68778e

Fixes:

    Traceback (most recent call last):
      ...
      File ".../ocrodjvu/lib/version.py", line 65, in __call__
        print('+ PyICU {0}'.format(pyicu.VERSION))
    AttributeError: 'NoneType' object has no attribute 'VERSION'