Drop support for python-djvulibre < 0.3.9.
Earlier versions of python-djvulibre lacked work-around for S-expression
serialization regression: https://bugs.debian.org/664626

Fixes:

    ======================================================================
    FAIL: tests.test_text_zones.test_print_sexpr
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File ".../lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File ".../ocrodjvu/tests/test_text_zones.py", line 38, in test_print_sexpr
        assert_equal(fp.getvalue(), out)
    AssertionError: '"je\xc5\xbc"' != '"je\\305\\274"'