utils: make smart_repr() return byte string.
This function was only used in contexts where byte strings were
expected.

Fixes: commit 6ad242f742c99ecc17e2622e8ec17870388698c8

Fixes:

    $ ocrodjvu --dry-run $(printf '\xD0\x90')
    Intermediate files were left in the '/tmp/ocrodjvu.V92tY_' directory.
    Traceback (most recent call last):
      File ".../ocrodjvu", line 7, in <module>
        _.main(sys.argv)
      File ".../cli/ocrodjvu.py", line 563, in main
        context.process(options.path, options.pages)
      File ".../cli/ocrodjvu.py", line 545, in process
        self._process(*args, **kwargs)
      File ".../cli/ocrodjvu.py", line 465, in _process
        logger.info('Processing {path}:'.format(path=utils.smart_repr(path, system_encoding)))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u0410' in position 1: ordinal not in range(128)

https://github.com/jwilk/ocrodjvu/issues/23